sudo: false
language: cpp

compiler: g++

install:
 - wget --directory-prefix $PREFIX/include
    https://raw.github.com/philsquared/Catch/master/single_include/catch.hpp

script:
- mkdir build 
- cd build
- make test 

